#!/usr/bin/env bash
# set -Eeuo pipefail

error() {
  echo "Error: $@" >&2
}

command_exists() {
  command -v "${1}" > /dev/null 2>&1
}

airport() {
  local AIRPORT_CMD='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport'

  if [[ ! -x "${AIRPORT_CMD}" ]]; then
    error 'Unable to find `airport` command.'
    return 1
  fi

  "${AIRPORT_CMD}" -I
}

signal_to_noise() {
  if ! command_exists bc; then
    error 'Uneable to find `bc` command.'
    return 1
  fi

  airport | grep -E 'agrCtlRSSI|agrCtlNoise' | awk '{print $2}' | sed 'N;s/\n/ - /g' | bc
}

signal_to_noise
